//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaAPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzeriaAPPEntities : DbContext
    {
        public PizzeriaAPPEntities()
            : base("name=PizzeriaAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientsPizza> IngredientsPizzas { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<OrderedPizza> OrderedPizzas { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
